### PR TITLE
Allow disabling of CURVE

### PR DESCRIPTION
**Pull request by akhilles**
Depends on https://github.com/jean-airoldie/zeromq-src-rs/pull/14.

### CODE REVIEW

**Comment by jean-airoldie** [comment]
I release 0.1.9 so you push an empty to commit or amend you commit to restart the CI.

**Comment by akhilles** [comment]
I think the `vendor` directory wasn't included in the 0.1.9 release. Maybe the submodule wasn't checked out when publishing?

**Comment by jean-airoldie** [comment]
Good catch, gotta love sub modules. Somehow my CI didn't catch that.

**Comment by jean-airoldie** [comment]
Alright I released 0.1.10, should be good.

**Comment by jean-airoldie** [comment]
Looks goo.

Not the biggest fan of default features but a guess there's no way around it without a breaking change.

**Pull request merged**
